---
#- name: Create user borg
#  ansible.builtin.user:
#    name: borg
#    password: $y$j9T$E2hwDdwVCX.O8xwll.KoW1$z/fYpv0VhS93w13t/RjPIYJwmBdN1xs8C3qcz81NEyB
#    create_home: yes
#  tags:
#    - server

#- name: Create catalog .ssh
#  ansible.builtin.file:
#    path: /home/borg/.ssh
#    state: directory
#    owner: borg
#    group: borg
#    mode: '0700'
#  tags:
#    - server


#- name: Change file
#  ansible.builtin.file:
#    path: /home/borg/.ssh/authorized_keys
#    state: touch
#    owner: borg
#    group: borg
#    mode: '0600'
#  tags:
#    - server


- name: Create backup catalog
  ansible.builtin.file:
    path: /var/backup
    state: directory
    owner: borg
    group: borg
    mode: '0700'
  tags:
    - server


- name: Format disk
  ansible.builtin.shell: mkfs.ext4 /dev/`lsblk | grep 5G | cut -c1-3`
  tags:
    - server


- name: Mount disk
  ansible.builtin.shell: mount /dev/`lsblk | grep 5G | cut -c1-3` /var/backup/
  tags:
    - server


- name: AutoMount
  ansible.builtin.shell: echo "/dev/`lsblk | grep 5G | cut -c1-3` /var/backup/ ext4 0 0" >> /etc/fstab
  tags:
    - server


- name: Permission backup catalog
  ansible.builtin.file:
    path: /var/backup/client
    state: directory
    owner: borg
    group: borg
    mode: '0700'
  tags:
    - server
