---
- name: tz setting
  ansible.builtin.copy:
    src: /usr/share/zoneinfo/Europe/Moscow
    dest: /etc/localtime
    remote_src: yes
  tags:
    - prepare

- name: update
  apt:
    update_cache=yes cache_valid_time=3600
  tags:
    - prepare

- name: install apt
  ansible.builtin.apt:
    pkg:
    - borgbackup
    - sshpass
  tags:
    - prepare

- name: Create user borg
  ansible.builtin.user:
    name: borg
    password: $y$j9T$E2hwDdwVCX.O8xwll.KoW1$z/fYpv0VhS93w13t/RjPIYJwmBdN1xs8C3qcz81NEyB
    create_home: yes
  tags:
    - prepare

- name: Create catalog .ssh
  ansible.builtin.file:
    path: /home/borg/.ssh
    state: directory
    owner: borg
    group: borg
    mode: '0700'
  tags:
    - prepare


- name: Change file
  ansible.builtin.file:
    path: /home/borg/.ssh/authorized_keys
    state: touch
    owner: borg
    group: borg
    mode: '0600'
  tags:
    - prepare

- name: Create catalog .ssh root
  ansible.builtin.file:
    path: /root/.ssh
    state: directory
    owner: borg
    group: borg
    mode: '0700'
  tags:
    - prepare
